name: LPCPlus
description: A chat formatting plugin for LuckPerms.
version: 3.7.1
main: me.wikmor.lpcplus.LPCPlus
authors:
  - WikMor
  - XCraftTM
api-version: 1.21
folia-supported: true
depend: [LuckPerms]
softdepend: [PlaceholderAPI]
commands:
  lpcplus:
    description: Reload the configuration of LPCPlus.
    permission: lpcplus.reload
    usage: "Usage: /lpcplus reload"
permissions:
  lpcplus.reload:
    description: Allows reloading the LPCPlus configuration.
    default: op
  lpcplus.colorcodes:
    description: Allows using '&' legacy color codes in chat.
    default: false
  lpcplus.rgbcodes:
    description: Allows using '&#RRGGBB' hex color codes in chat.
    default: false
  lpcplus.minimessage:
    description: Allows using MiniMessage formatting (colors, gradients, hover/click, etc.) in chat.
    default: false

